version: '3.8'

services:
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
      target: base
    command: sh -c "npm run dev & php artisan serve --host=0.0.0.0 --port=8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ./admin-service:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
